AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  GetLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: src/handler/
      Handler: get.handler
      Runtime: nodejs12.x  
      Events:
        GetLambdaApi:
          Type: Api
          Properties:
            Path: /{table}/{id}
            Method: get
  
  GetAllLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: src/handler/
      Handler: getAll.handler
      Runtime: nodejs12.x  
      Events:
        GetLambdaApi:
          Type: Api
          Properties:
            Path: /{table}
            Method: get
