AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  DYNAMO_URL:
    Type: String
    Description: Dynamodb host url
  DYNAMO_REGION:
    Type: String
    Description: Dynamodb host url
    Default: local

Resources:
    GetLambdaFunction:
      Type: 'AWS::Serverless::Function'
      Properties:
        CodeUri: src/handler/
        Handler: dbGet.handler
        Runtime: nodejs12.x  
        Environment:
          Variables:
            DYNAMO_URL: !Ref DYNAMO_URL
            DYNAMO_REGION: !Ref DYNAMO_REGION
        Events:
          GetLambdaApi:
            Type: Api
            Properties:
              Path: /{table}/{id}
              Method: get
    GetAllLambdaFunction:
      Type: 'AWS::Serverless::Function'
      Properties:
        CodeUri: src/handler/
        Handler: dbGetAll.handler
        Runtime: nodejs12.x  
        Environment:
          Variables:
            DYNAMO_URL: !Ref DYNAMO_URL
            DYNAMO_REGION: !Ref DYNAMO_REGION
        Events:
          GetLambdaApi:
            Type: Api
            Properties:
              Path: /{table}
              Method: get
    
    CloudWatchEventLambdaFunction:
      Type: 'AWS::Serverless::Function'
      Properties:
        CodeUri: src/handler/
        Handler: cloudWatchEvent.handler
        Runtime: nodejs12.x  
        Events:
          CloudWatchEventLambdaSchedule:
            Type: Schedule
            Properties:
              Schedule: 'rate(1 minute)'
              # Schedule: 'cron(1 * * * ? *)'

Outputs:
  GetLambdaApi:
    Description: "API Gateway endpoint URL for GetLambdaFunction on dev stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/"
  GetLambdaFunction:
    Description: "Get Lambda Function ARN"
    Value: !GetAtt GetLambdaFunction.Arn

  PostLambdaApi:
    Description: "API Gateway endpoint URL for GetLambdaFunction on dev stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/"
  PostLambdaFunction:
    Description: "Post Lambda Function ARN"
    Value: !GetAtt PostLambdaFunction.Arn
  
  CloudWatchEventLambdaSchedule:
    Description: "CloudWatch Event schedule for CloudWatchEventLambdaFunction"
    Value: "rate(1 minute)"
  CloudWatchEventLambdaFunction:
    Description: "CloudWatch Event Lambda Function ARN"
    Value: !GetAtt CloudWatchEventLambdaFunction.Arn